import { expect, test } from '@playwright/test';
test('sign up, create, edit, delete and sign in again', async ({ page }) => {
  const email = `browser-${Date.now()}-${Math.random().toString(36).slice(2)}@example.test`;
  const password = 'Browser-test-password-2026!';
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your next great project.' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign up', exact: true }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByText(email, { exact: true })).toBeVisible();
  await page.getByLabel('Project name', { exact: true }).fill('Launch website');
  await page.getByLabel('Description', { exact: true }).fill('Ship a useful first version.');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Launch website', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit Launch website', exact: true }).click();
  await page.getByLabel('Project name', { exact: true }).fill('Launch mobile');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Launch mobile', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Delete Launch mobile', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm delete', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Launch mobile', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByText(email, { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Email', { exact: true })).toBeVisible();
});
